In [1]:
import os
os.chdir("/content/drive/MyDrive/Colab Notebooks/推荐系统/推荐系统算法复现/ml-100k")
import numpy as np
import pandas as pd

In [2]:
def loadData():
    f = open('u.data')
    data = []
    for i in range(100000):
        h = f.readline().split('\t')
        h = list(map(int, h))
        data.append(h[0:3])
    f.close()
    return data

In [8]:
df = pd.DataFrame(loadData())
df.columns = ['user_id','item_id','rating']
df_sorted = df.sort_values(by='user_id', ascending=True)
# 将评分大于等于4的评分记为1，其他记为0
df_sorted.rating = df_sorted.rating.apply(lambda x:1 if x >=4 else 0)
df_sorted

user_id  item_id  rating
66567        1       55       1
62820        1      203       1
10207        1      183       1
9971         1      150       1
22496        1       68       1
...        ...      ...     ...
96823      943      427       1
70902      943       12       1
84518      943      284       0
72321      943       62       0
70713      943      210       1

[100000 rows x 3 columns]

In [9]:
df_sorted.to_csv("user_item2.csv")

In [10]:
# 生成用户和物体的共现矩阵
from scipy.sparse import coo_matrix

# 为用户和物品创建唯一的数字索引
user_ids = df_sorted['user_id'].astype("category").cat.codes
item_ids = df_sorted['item_id'].astype("category").cat.codes

# 创建共现矩阵
cooccurrence_matrix = coo_matrix(
    (df_sorted['rating'], (user_ids, item_ids)),
    shape=(df_sorted.user_id.nunique(), df_sorted.item_id.nunique())
)

co_mat = cooccurrence_matrix.toarray()

print(co_mat.shape) # (用户数量，物体数量)
print(co_mat)

(943, 1682)
[[1 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [11]:
pd.DataFrame(co_mat).to_csv('co_mat2.csv')